# Generated by Django 3.2.12 on 2022-07-25 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_alter_page_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='page',
        ),
        migrations.RemoveField(
            model_name='post',
            name='reply_to',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
        migrations.RemoveField(
            model_name='page',
            name='id',
        ),
        migrations.AlterField(
            model_name='page',
            name='uuid',
            field=models.CharField(max_length=64, primary_key=True, serialize=False, unique=True),
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
