FROM python:3.10.4

ENV VAR1=10

ENV PYTHONDONTWRITEBYTECODE=1

ENV PYTHONUNBUFFERED=1

COPY Pipfile Pipfile.lock ./
RUN python3 -m pip install --upgrade pip
RUN pip install pipenv
RUN pipenv install --dev --system

WORKDIR /app
COPY ./microservice/ .

#ENV PORT 8000
#ENV HOST "0.0.0.0"

#EXPOSE 8001

#CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "5000"]
CMD uvicorn main:app --reload --host 0.0.0.0 --port 5000
