version: '3.7'
services:
  web:
    build: .
    command: python manage.py runserver 127.0.0.1:8000
    volumes:
      - ./innotter:/app
    ports:
      - 8000:8000
    env_file:
      - ./.env
    depends_on:
      - db


  db:
    ports:
      - "5432:5432"
    image: postgres:12.0-alpine
    volumes:
      - "/var/lib/postgresql/data/"
    environment:
      - POSTGRES_USER=hello_django
      - POSTGRES_PASSWORD=hello_django
      - POSTGRES_DB=hello_django_dev


      # Redis
  redis:
    image: redis:6.0.16
    hostname: redis

  # RabbitMQ
  rabbit:
    hostname: rabbit
    image: rabbitmq:3.9.13
    env_file:
      - ./.env
    ports:
      - "5672:5672"
      - "15672:15672"


   # Celery worker
  worker:
      build:
          context: .
          dockerfile: Dockerfile
      command: app/run_celery.sh
      env_file:
        - ./.env
      links:
          - db
          - rabbit
          - redis
      depends_on:
          - rabbit
          - db
