version: '3.7'
services:
  web:
    build: .
    volumes:
      - ./innotter:/app
    ports:
      - 8000:8000
    env_file:
      - ./.env
    depends_on:
      - db
#      - rabbit
#      - redis
#      - worker


  db:
    restart: always
    ports:
      - 5432:5432
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/

    environment:
      - POSTGRES_USER=hello_django
      - POSTGRES_PASSWORD=hello_django
      - POSTGRES_DB=hello_django_dev
      - POSTGRES_HOST_AUTH_METHOD=trust


      # Redis
  redis:
    image: redis:6.0.16
    hostname: redis

  # RabbitMQ
  rabbitmq:
    hostname: rabbitmq
    image: rabbitmq:3.9.13
    restart: always
    env_file:
      - ./.env
    ports:
      - 5672:5672
      - 15672:15672


   # Celery worker
  worker:
      build:
          context: .
          dockerfile: Dockerfile
      command: ./run_celery.sh

      env_file:
        - ./.env
      links:
          - db
          - rabbitmq
          - redis
      depends_on:
          - rabbitmq
          - db


  localstack:
    container_name: localstack
    environment:
      - AWS_DEFAULT_REGION=us-east-1
      - EDGE_PORT=4566
      - SERVICES=ses
    image: localstack/localstack:latest
    ports:
      - 4566:4566
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  postgres_data: