version: '3.7'
services:
  web:
    build: .
    volumes:
      - ./innotter:/app
    ports:
      - 8000:8000
    env_file:
      - ./.env
    depends_on:
      - db


  db:
    ports:
      - 5432:5432
    image: postgres:12.0-alpine
    volumes:
      - "/var/lib/postgresql/data/"
    environment:
      - POSTGRES_USER=hello_django
      - POSTGRES_PASSWORD=hello_django
      - POSTGRES_DB=hello_django_dev
