version: '3.7'
services:
  web:
    build: .
    volumes:
      - ./innotter:/app
    ports:
      - 8000:8000
    env_file:
      - ./.env
    depends_on:
      - db
#      - rabbit
#      - redis
#      - worker


  db:
    restart: always
    ports:
      - 5432:5432
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/

    environment:
      - POSTGRES_USER=hello_django
      - POSTGRES_PASSWORD=hello_django
      - POSTGRES_DB=hello_django_dev
      - POSTGRES_HOST_AUTH_METHOD=trust


      # Redis
  redis:
    image: redis:6.0.16
    hostname: redis

  # RabbitMQ
  rabbitmq:
    hostname: rabbitmq
#    image: rabbitmq:3.9.13
    image: rabbitmq:3.9.13-management-alpine
    restart: always
    env_file:
      - ./.env
    ports:
      - 5672:5672
      - 15672:15672

# rabbitmqctl add_user test test
# rabbitmqctl set_user_tags test administrator
# rabbitmqctl set_permissions -p / test ".*" ".*" ".*"

   # Celery worker
  worker:
      build:
          context: .
          dockerfile: Dockerfile
      command: ./run_celery.sh

      env_file:
        - ./.env
      links:
          - db
          - rabbitmq
          - redis
      depends_on:
          - rabbitmq
          - db


  localstack:
    container_name: localstack
    environment:
      - AWS_DEFAULT_REGION=us-east-1
      - EDGE_PORT=4566
      - SERVICES=ses
    image: localstack/localstack:latest
    ports:
      - 4566:4566
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock


  # MICROSERVICE
  stats:
    build:
      context: .
      dockerfile: Dockerfile.microservice
    volumes:
      - ./statistics:/app
    ports:
      - 5000:5000
    depends_on:
      - dynamodb

  dynamodb:
    image: amazon/dynamodb-local
    container_name: my-dynamodb-data
    hostname: dynamodb
    restart: always
    environment:
      - DYNAMO_ENDPOINT=http://dynamodb:8000
    volumes:
      - ./my-dynamodb-data:/home/dynamodblocal/data
    ports:
      - 8001:8001
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath /home/dynamodblocal/data/"

volumes:
  postgres_data: