# Generated by Django 3.2.12 on 2022-07-20 10:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20220714_0859'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='tags',
        ),
        migrations.AlterField(
            model_name='page',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='page',
            name='follow_requests',
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name='requests',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name='page',
            name='followers',
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name='follows',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name='page',
            name='name',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='page',
            name='uuid',
            field=models.CharField(max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
